ChatAPI/urls.py
from django.urls import path, re_path, include
from rest_framework import routers
from django.contrib.auth import views as auth_views
from . import consumers
from .views import *

router = routers.DefaultRouter()
router.register(r'', Constance, basename='constance')


urlpatterns = [
    path('', index, name='index'),

    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-reset/', ResetPasswordView.as_view(), name='password-reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
             auth_views.PasswordResetConfirmView.as_view(template_name='ChatAPI/password_reset/password_reset_confirm.html'),
             name='password_reset_confirm'),
    path('password-reset-complete/',
             auth_views.PasswordResetCompleteView.as_view(template_name='ChatAPI/password_reset/password_reset_complete.html'),
             name='password_reset_complete'),

    path('chats/', ChatsView.as_view(), name='chats'),

    path('create-chat/', GroupChatCreateView.as_view(), name='create-chat'),
    path('chat/<int:chat_id>/', ChatView.as_view(), name='chat'),

    path('direct/', DirectChat.as_view(), name='direct_or_create'),

    path('chat/<int:chat_id>/leave/', LeaveGroupChat.as_view(), name='leave'),
    path('delete_message/<int:message_id>/', DeleteMessage.as_view(), name='delete_message'),
    path('chat/<int:chat_id>/peer/', PeerGroupChatView.as_view(), name='peer'),
    path('chat/<int:chat_id>/peer/delete_chat/', DeleteGroupChat.as_view(), name='delete_chat'),
    path('chat/<int:chat_id>/peer/add_user/', AddGroupUser.as_view(), name='add_user'),
    path('chat/<int:chat_id>/peer/remove_user/<int:user_id>/', RemoveGroupUser.as_view(), name='remove_user'),
    # path('chat/<int:chat_id>/peer/add_admin/<int:user_id>/', AddGroupAdmin.as_view(), name='add_admin'),

    # test
    path('test/', websocketest),
    path('api/constance/', include(router.urls))
]

Chat_Django/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('ChatAPI.urls')),
    path('', include('friend_requests.urls'))
] + debug_toolbar_urls()

friend_requests/urls.py
from django.urls import path, re_path

from friend_requests.views import *


app_name = 'fri_req'

urlpatterns = [
    path('search_user/', search_users_view, name='search_users'),
    path('send_friend_request/<int:user_id>/', send_friend_request, name='send_friend'),

    path('incoming_friend_requests/', incoming_friend_requests, name='incoming_friend_requests'),
    path('handle_friend_request/<int:request_id>/<str:action>/', handle_friend_request, name='handle_friend_request'),

    path('friends/', friends_list, name='friends'),
    path('friends/<int:friend_id>/delete_friend', delete_friend, name='delete_friend'),

    path('profile/<int:user_id>/', profile, name='profile'),

    path('send_email/', send_hello_email, name='send_hello'),





]

friend_requests/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from ChatAPI.models import *


class FriendRequest(models.Model):
    from_user = models.ForeignKey(User, related_name='from_request', on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name='to_request', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('from_user', 'to_user')

    def __str__(self):
        return f'{self.from_user} -> {self.to_user}'


class Notification(models.Model):
    class Type(models.TextChoices):
        MESSAGE = ('message', 'сообщение')
        REQUEST = ('request', 'запрос')

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notification')
    type = models.TextField(max_length=7, choices=Type.choices)
    content = models.TextField(max_length=100)
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} -> {self.type} -> {self.content[:50]}"

friend_requests/forms.py
import datetime
from django import forms
from .models import *


class ProfileForm(forms.ModelForm):
    this_year = datetime.date.today().year
    date_birth = forms.DateField(widget=forms.SelectDateWidget(years=tuple(range(this_year - 100, this_year - 5))))

    class Meta:
        model = User
        fields = ('image', 'username', 'first_name', 'last_name', 'date_birth', )

friend_requests/views.py
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
from rest_framework.response import Response

from ChatAPI.tasks import send_message
from Chat_Django import settings
from Chat_Django.settings import DEFAULT_FROM_EMAIL
from .forms import ProfileForm
from .models import *
from ChatAPI.models import *
from ChatAPI.serializers import UserSerializer
from friend_requests.filters import *
from .serializers import *


logger = logging.getLogger(__name__)

@login_required
def search_users_view(request):
    user = request.user
    friend_ids = user.friends.values_list('id', flat=True)
    queryset = User.objects.exclude(id__in=friend_ids).exclude(id=user.id)
    query_filter = UserNameFilter(request.GET, queryset=queryset)

    friend_request_ids = FriendRequest.objects.filter(from_user=user).values_list('to_user_id', flat=True)
    users_with_status = [
        {
            'user': _user,
            'is_subscribed': _user.id in friend_request_ids
        }
        for _user in query_filter.qs
    ]

    return render(request, 'friend_requests/user_search.html', context={
        'filter': query_filter,
        'users': users_with_status,
        'title': 'Пользователи',
    })


@login_required
def send_friend_request(request, user_id):
    if request.method == 'POST':

        from_user = request.user
        to_user = get_object_or_404(User, pk=user_id)

        if to_user == from_user:
            messages.error(request, _('Вы не можете добавлять в друзья себя самого.'))
            return redirect(reverse_lazy('fri_req:search_users'), kwargs={'user_id': user_id})

        FriendRequest.objects.create(from_user=from_user, to_user=to_user)
        messages.success(request, f'Ваш запрос к {to_user.username} на добавление в друзья успешно отправлен!')
        return redirect(reverse_lazy('fri_req:search_users'), kwargs={'user_id': user_id})


@login_required
def incoming_friend_requests(request):
    requests = FriendRequest.objects.filter(to_user=request.user)
    return render(request, 'friend_requests/incoming_friend_requests.html', {
        'requests': requests,
        'title': 'Входящие запросы на добавление в друзья'
    })


@login_required
def handle_friend_request(request, request_id, action):
    friend_request = get_object_or_404(FriendRequest, id=request_id, to_user=request.user)

    if action == 'accept':
        friend_request.from_user.friends.add(friend_request.to_user)
        friend_request.delete()
        messages.success(request, f"Вы теперь друзья с {friend_request.from_user.username}.")
        return redirect('fri_req:incoming_friend_requests')
    elif action == 'decline':
        friend_request.delete()
        messages.success(request, f"Запрос от {friend_request.from_user.username} отклонен.")
        return redirect('fri_req:incoming_friend_requests')


@login_required
def friends_list(request, ):
    query = request.user.friends.all()
    Serializer = FriendsSerializer(query, many=True).data

    return render(request, 'friend_requests/friends_list.html', {
        'friends': Serializer,
        'title': 'Список друзей',
    })


@login_required
def profile(request, user_id):
    if user_id == request.user.id:
        profile = request.user
    else:
        profile = get_object_or_404(User, pk=user_id)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Данные успешно изменены.')
            return redirect(reverse_lazy('fri_req:profile', kwargs={'user_id': request.user.id}))
    else:
        form = ProfileForm(instance=profile)

        serializer = ProfileSerializer(profile, many=False).data

        return render(request, 'friend_requests/profile.html', context={
            'serializer': serializer,
            'form': form,
        })


@login_required
def delete_friend(request, friend_id):
    user = request.user
    friend = get_object_or_404(User, id=friend_id)
    user.friends.remove(friend)
    return redirect('friend_requests:friends')


@login_required
def send_hello_email(request):
    if request.method == 'POST':
        send_message.delay(request.user.username, request.user.email)
        logger.info('celery %s success ', send_message.__name__)
        return redirect('chats')

friend_requests/templates/friend_requests/friends_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <h1>{{ title }}</h1>
    {% if friends %}
        <ul>
            {% for friend in friends %}
                <li>{{ friend.username }}</li>
                <form action="{% url 'direct_or_create' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ friend.id }}">
                <button type="submit">Написать</button>
                </form>
            <form method="post" action="{% url 'fri_req:delete_friend' friend.id %}" style="display: inline;">
            {% csrf_token %}
            <button type="submit" onclick="return confirm('Вы уверены, что хотите удалить друга??')">Удалить из друзей</button>
            </form>

            {% endfor %}
        </ul>
    {% else %}
        <p>У вас пока нет друзей.</p>
    {% endif %}

</body>
</html>

friend_requests/templates/friend_requests/incoming_friend_requests.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <h1>{{ title }}</h1>
    {% if requests %}
        <ul>
            {% for req in requests %}
                <li>
                    {{ req.from_user.username }} хочет добавить вас в друзья.
                    <a href="{% url 'fri_req:handle_friend_request' req.id 'accept' %}">Принять</a> |
                    <a href="{% url 'fri_req:handle_friend_request' req.id 'decline' %}">Отклонить</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>У вас нет входящих запросов на добавление в друзья.</p>
    {% endif %}

    <form method="post" action="{% url 'fri_req:send_hello' %}">
        {% csrf_token %}
        <button type="submit">Отправить письмо</button>
    </form>
</body>
</html>

friend_requests/templates/friend_requests/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Профиль: {{ serializer.username }}</title>
</head>
<body>
    <div>Профиль: {{ serializer.username }}</div>


    <img src="{{ serializer.image.url }}" alt="Аватар">


    {% if request.user.id == serializer.id %}
    <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for f in form %}
                <div>
                <label for="{{ f.id_for_label }}">{{ f.label }}:</label>
                {{ f }}

                </div>
            {% endfor %}
            {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
            <p><button type="submit"> Сохранить изменения</button></p>
        </form>
    {% endif %}

    {% if request.user.id != serializer.id %}
        <div>Ник: {{ serializer.username }}</div>
        <div>Почта: {{ serializer.email }}</div>
        {% if serializer.first_name %}
            <div>Имя: {{ serializer.first_name }} {% else %} Имя: не установлено.</div>
        {% endif %}
        <br>
        {% if serializer.last_name %}
            <div>Фамилия: {{ serializer.last_name }} {% else %} Фамилия: не установлено.</div>
        {% endif %}
        <br>
        {% if serializer.date_birth %}
            <div>Фамилия: {{ serializer.date_birth }} {% else %} Дата рождения: не установлено.</div>
        {% endif %}
    {% endif %}


</body>
</html>

friend_requests/templates/friend_requests/user_search.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>

         <h2>Поиск пользователя</h2>
                <form method="get" action="{% url 'fri_req:search_users' %}">
                    {% for f in filter.form %}
                        <p class="form-group">
                            <label class="form-control" for="{{ f.id_for_label }}">{{ f.label }}:</label>
                            {{ f }}
                        </p>
                        {% if f.errors %}
                            <div class="form-error">{{ f.errors }}</div>
                        {% endif %}
                    {% endfor %}
                    <button class="btn btn-primary" type="submit">Найти</button>
                </form>
         <hr>
         {% for message in messages %}
        <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
         <hr>

        <div class="user-list">
    <h2>Пользователи</h2>
    {% for user_data in users %}
        <div class="user-item">
            <h1><a href="{% url 'fri_req:profile' user_data.user.id %}">{{ user_data.user.username }}</a></h1>
            {% if user_data.is_subscribed %}
                <span>Заяка отправлена</span>
            {% else %}
                <form method="post" action="{% url 'fri_req:send_friend' user_data.user.id %}">
                    {% csrf_token %}
                    <button type="submit">Отправить заявку в друзья</button>
                </form>
            {% endif %}
        </div>
    {% endfor %}
        </div>

</body>
</html>